### ISSUE TITLE
Quic connection with nginx.org fails

### ISSUE THREAD

**Issue by zhkl0228** [ptrd/flupke#12] opened 2024-06-18 15:23 UTC
```
public void testFlupke() throws Exception {
        URI serverUrl = URI.create("https://quic.nginx.org/test");
        HttpRequest request = HttpRequest.newBuilder()
                .uri(serverUrl)
                .timeout(Duration.ofSeconds(30))
                .build();

        HttpClient client = Http3Client.newBuilder()
                .logger(new SysOutLogger())
                .connectTimeout(Duration.ofSeconds(30))
                .build();
        HttpResponse<String> httpResponse = client.send(request, HttpResponse.BodyHandlers.ofString());
        System.out.println(httpResponse.body());
    }
```

**Comment by ptrd** [comment] 2024-06-18 16:57
Hi,
Thanks for your interest in Flupke.
It would help me a lot if you would describe what the problem is. I now feel like you are giving me a puzzle. I'm not in to puzzles. I like to help you but i would also like to spend as little time on it as needed, so I can spend my valuable time on creating new features.
Please help me in helping you. I'm, after all, a human being, you can just talk to me ;-)

**Comment by zhkl0228** [comment] 2024-06-18 23:12
I apologize for my poor English, the above test run will fail

**Comment by ptrd** [comment] 2024-06-19 06:31
Your English is ok, don't worry, i'm not a native speaker myself.

It fails with an exception I guess? Can you show the stacktrace?

**Comment by zhkl0228** [comment] 2024-06-19 06:53
53:26.393 Error: Inconsistency error in congestion controller; attempt to set bytes in-flight below 0
53:26.402 Error: Discarding packet (74 bytes) that cannot be decrypted (net.luminis.quic.crypto.MissingKeysException: Missing keys for encryption level Handshake (keys not installed))

java.net.ConnectException: Handshake error: Server closed connection: TLS error 40: handshake failed

	at net.luminis.quic.core.QuicClientConnectionImpl.connect(QuicClientConnectionImpl.java:373)
	at net.luminis.quic.core.QuicClientConnectionImpl.connect(QuicClientConnectionImpl.java:322)
	at net.luminis.http3.impl.Http3ClientConnectionImpl.connect(Http3ClientConnectionImpl.java:92)
	at net.luminis.http3.Http3Client.send(Http3Client.java:134)

**Comment by zhkl0228** [comment] 2024-06-19 06:54
flupke-0.5.3

**Comment by ptrd** [comment] 2024-06-19 16:19
I reproduced the problem and from the Wireshark capture I can see that nginx immediately sends a "connection close". I have no clue why, asked the nginx people for help.

**Comment by ptrd** [comment] 2024-07-08 08:49
The reason this fails is that this server uses ECDSA certificate (public key algorithm id-ecPublicKey) on curve P-384. 
Unfortunately, this is currently not supported by kwik / agent15.
I'm closing this issue, because it is definitely not an issue in Flupke. Feel free to create an issue for this in Kwik project. Either way, I will fix this.

**Closed by ptrd** 2024-07-08 08:49 UTC

**Comment by ptrd** [comment] 2024-08-04 19:31
Fixed in https://github.com/ptrd/kwik/commit/373f359264d89bebb9b7b7de0242e4a63ec41d2d
